- platform: foscam
  ip: 192.168.2.14
  port: 80
  username: foscam
  password: !secret foscam_c1
#- platform: local_file
#  name: cancello
#  file_path: /home/hass/camera/gate.jpg

- platform: push
  name: motion cancello
  buffer: 3
  timeout: 5
  webhook_id: gate_webhook 

