homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  latitude: 45.493400
  longitude: 11.106900
  elevation: 430
  unit_system: metric
  time_zone: Europe/Rome
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # see https://www.home-assistant.io/components/http/
  api_password: !secret http_password
  base_url: !secret base_url
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
  trusted_networks:
    - 127.0.0.1
    - 192.168.2.0/24


# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Sensors
sensor:
  # Weather prediction
  - platform: yr

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml


zwave:
  usb_path: /dev/zwave
  network_key: !secret zwave_network_key

tradfri:
  host: 192.168.2.30

google_assistant: !include google_assistant.yaml
