homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  latitude: 45.493400
  longitude: 11.106900
  elevation: 430
  unit_system: metric
  time_zone: Europe/Rome
  # Customization file
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /home/hass/camera
    - /tmp
  auth_providers:
   - type: legacy_api_password
     api_password: !secret http_password
   - type: trusted_networks
     trusted_networks:
       - 192.168.2.0/24
       - fd00::/8

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # see https://www.home-assistant.io/components/http/
  # api_password: !secret http_password
  base_url: !secret base_url
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1


# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

recorder:
  purge_keep_days: 5
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sun.sun # Don't record sun data
      - sensor.last_boot # Comes from 'systemmonitor' sensor platform
      - sensor.date

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    language: 'it'
  - platform: marytts
    host: 'localhost'
    port: 59125
    codec: 'wav'
    voice: 'cmu-slt-hsmm'
    language: 'it'

# Cloud
cloud:

group: !include groups.yaml
script: !include scripts.yaml


zwave:
  usb_path: /dev/zwave
  network_key: !secret zwave_network_key

tradfri:
  host: 192.168.2.30

#google_assistant: !include google_assistant.yaml

camera: !include cameras.yaml

sensor: !include_dir_merge_list sensors

input_boolean: !include input_boolean.yaml

automation: !include automations.yaml
automation old: !include_dir_merge_list automations




notify: !include notify.yaml

telegram_bot:
  #platform: webhooks
  platform: polling
  api_key: !secret telegram_token
  trusted_networks:
    - 149.154.167.197/32
    - 149.154.167.198/31
    - 149.154.167.200/29
    - 149.154.167.208/28
    - 149.154.167.224/29
    - 149.154.167.232/31
  allowed_chat_ids:
    - 73496590
    - 84015820
    - 609301127


alexa:
  smart_home:

switch:
  - platform: broadlink
    host: 192.168.2.28
    mac: 'A1:26:F4:34:EA:34'
    switches:
      tv_lg:
        friendly_name: "TV"
        command_on: "JgCYAAABKJMSExEUETkRFBEUERMSExEUETkRORETEjgRORE5ETgSOBEUERQRFBE4EhMRFBEUERQRORE4ETkRFBE5ETgSOBE5EQAFKgABKUcUAAxdAAEoShEADF4AAShKEQAMXQABKEoRAAxeAAEoShEADF0AASlJEQAMXgABKEoRAAxdAAEpShEADF0AAShKEQAMXgABKUkRAA0F"
        command_off: "JgCYAAABKJMSExEUETkRFBEUERMSExEUETkRORETEjgRORE5ETgSOBEUERQRFBE4EhMRFBEUERQRORE4ETkRFBE5ETgSOBE5EQAFKgABKUcUAAxdAAEoShEADF4AAShKEQAMXQABKEoRAAxeAAEoShEADF0AASlJEQAMXgABKEoRAAxdAAEpShEADF0AAShKEQAMXgABKUkRAA0F"
      #cancellorf:
      #  friendly_name: "cancelloRF"
      #  command_on: "b2063400250c250c0d240d240d240d240d240d24240c240d250d240c0d240d24250d0d240d240d24250d0c240d000172240d240c0d240d2400000000"
      #  command_off: "b2063400250c250c0d240d240d240d240d240d24240c240d250d240c0d240d24250d0d240d240d24250d0c240d000172240d240c0d240d2400000000"


weather:
  - platform: openweathermap
    api_key: 21e57a6e95e983d5b45e6c3b731a6526
